"""Script to generate the 01_eda_supplementary.ipynb notebook."""
import json
import os

# Build the notebook
cells = []


def md_cell(source):
    return {
        'cell_type': 'markdown',
        'metadata': {},
        'source': source if isinstance(source, list) else [source],
    }


def code_cell(source):
    return {
        'cell_type': 'code',
        'metadata': {},
        'source': source if isinstance(source, list) else [source],
        'outputs': [],
        'execution_count': None,
    }


# === Title ===
cells.append(md_cell([
    '# Phase 1 EDA — Supplementary Investigation\n',
    '\n',
    'This notebook addresses all gaps identified in the **Phase 0.5 and Phase 1 review**\n',
    '(`documentation/supplementary_docs/0_1_review.md`).\n',
    '\n',
    '**Sections:**\n',
    '1. FIRST_BREAK_TIME vs SPARE1 comparison\n',
    '2. MODELLED_BREAK_TIME investigation\n',
    '3. FIRST_BREAK_AMPLIT and FIRST_BREAK_VELOCITY summary\n',
    '4. Spatial coordinate sanity check\n',
    '5. Resampling comparison for Lalor\n',
    '6. SNR proxy redefinition and visualization example reclassification\n',
    '7. Brunswick gather width memory estimate\n',
    '\n',
    '**Outputs:**\n',
    '- `results/eda/supplementary_report.json`\n',
    '- `results/eda_plots/supplementary/*.png`\n',
    '- Updated `results/visualization_examples.json`\n',
]))

# === Cell 1: Configuration & Setup ===
cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 1 — Configuration & Setup\n',
    '# ============================================================\n',
    'import sys, os, json, time, warnings\n',
    'import numpy as np\n',
    'import h5py\n',
    'import matplotlib\n',
    'matplotlib.use("Agg")  # non-interactive backend for Colab\n',
    'import matplotlib.pyplot as plt\n',
    'import yaml\n',
    '\n',
    '# Mount Drive (idempotent)\n',
    'try:\n',
    '    from google.colab import drive\n',
    '    drive.mount("/content/drive", force_remount=False)\n',
    '    IN_COLAB = True\n',
    'except ImportError:\n',
    '    IN_COLAB = False\n',
    '\n',
    '# Load project config\n',
    'REPO_ROOT = "/content/drive/MyDrive/seismic-first-break-picking" if IN_COLAB else os.getcwd()\n',
    'config_path = os.path.join(REPO_ROOT, "configs", "datasets.yaml")\n',
    'with open(config_path) as f:\n',
    '    CFG = yaml.safe_load(f)\n',
    '\n',
    'ASSET_NAMES = CFG["assets"]["names"]\n',
    'HDF5_GROUP = "TRACE_DATA/DEFAULT"\n',
    '\n',
    '# Create supplementary plots directory\n',
    'SUPP_PLOT_DIR = os.path.join(REPO_ROOT, CFG["paths"]["eda_plots"], "supplementary")\n',
    'SUPP_JSON_DIR = os.path.join(REPO_ROOT, CFG["paths"]["eda_json"])\n',
    'os.makedirs(SUPP_PLOT_DIR, exist_ok=True)\n',
    'os.makedirs(SUPP_JSON_DIR, exist_ok=True)\n',
    '\n',
    '# Import shared utilities\n',
    'sys.path.insert(0, os.path.join(REPO_ROOT, "src"))\n',
    'from data.eda_utils import open_hdf5, apply_segy_scale, make_json_safe\n',
    '\n',
    '# Helper: open all assets\n',
    'def open_all_assets():\n',
    '    handles = {}\n',
    '    for name in ASSET_NAMES:\n',
    '        meta = CFG["asset_meta"][name]\n',
    '        path = os.path.join(REPO_ROOT, CFG["paths"]["extracted"], meta["extracted_file"])\n',
    '        f, grp = open_hdf5(path)\n',
    '        handles[name] = {"file": f, "grp": grp, "meta": meta}\n',
    '    return handles\n',
    '\n',
    '# Supplementary report accumulator\n',
    'supp_report = {}\n',
    '\n',
    'print("Configuration loaded. Assets:", ASSET_NAMES)\n',
    'print("Supplementary plots dir:", SUPP_PLOT_DIR)\n',
]))

# === Section 1: FIRST_BREAK_TIME vs SPARE1 ===
cells.append(md_cell([
    '## Section 1 — FIRST_BREAK_TIME vs SPARE1 Comparison\n',
    '\n',
    'For each asset, load both FIRST_BREAK_TIME and SPARE1 for a random sample of 5000 labeled traces.\n',
    'Compute the difference. Plot a histogram of the differences.\n',
    'If they are identical, document that SPARE1 is confirmed as the sole ground truth field.\n',
    'If they differ, document how and by how much.\n',
    '\n',
    '**Key context:** Phase 0.5 found `n_both_labeled: 0` for all assets, meaning that for every asset,\n',
    'the existing comparison function found zero traces where both SPARE1 > 0 AND FIRST_BREAK_TIME > 0.\n',
    'This section investigates WHY that happened and whether FIRST_BREAK_TIME contains anything useful.\n',
]))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 2 — Section 1: FIRST_BREAK_TIME vs SPARE1\n',
    '# ============================================================\n',
    'handles = open_all_assets()\n',
    'section1_results = {}\n',
    '\n',
    'N_SAMPLE = 5000\n',
    'rng = np.random.RandomState(42)\n',
    '\n',
    'fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n',
    'axes = axes.ravel()\n',
    '\n',
    'for i, name in enumerate(ASSET_NAMES):\n',
    '    grp = handles[name]["grp"]\n',
    '    meta = handles[name]["meta"]\n',
    '    \n',
    '    spare1 = grp["SPARE1"][:].ravel().astype(np.float64)\n',
    '    \n',
    '    result = {"asset": name}\n',
    '    \n',
    '    if "FIRST_BREAK_TIME" in grp:\n',
    '        fbt = grp["FIRST_BREAK_TIME"][:].ravel().astype(np.float64)\n',
    '        result["fbt_present"] = True\n',
    '        result["fbt_shape"] = list(grp["FIRST_BREAK_TIME"].shape)\n',
    '        result["fbt_dtype"] = str(grp["FIRST_BREAK_TIME"].dtype)\n',
    '        result["spare1_shape"] = list(grp["SPARE1"].shape)\n',
    '        result["spare1_dtype"] = str(grp["SPARE1"].dtype)\n',
    '        \n',
    '        # Characterize FIRST_BREAK_TIME values\n',
    '        fbt_zero = int(np.sum(fbt == 0))\n',
    '        fbt_neg = int(np.sum(fbt < 0))\n',
    '        fbt_pos = int(np.sum(fbt > 0))\n',
    '        result["fbt_count_zero"] = fbt_zero\n',
    '        result["fbt_count_negative"] = fbt_neg\n',
    '        result["fbt_count_positive"] = fbt_pos\n',
    '        result["fbt_total"] = len(fbt)\n',
    '        \n',
    '        # Characterize SPARE1 values\n',
    '        s1_zero = int(np.sum(spare1 == 0))\n',
    '        s1_neg = int(np.sum(spare1 < 0))\n',
    '        s1_pos = int(np.sum(spare1 > 0))\n',
    '        result["spare1_count_zero"] = s1_zero\n',
    '        result["spare1_count_negative"] = s1_neg\n',
    '        result["spare1_count_positive"] = s1_pos\n',
    '        result["spare1_total"] = len(spare1)\n',
    '        \n',
    '        # Check overlap: where both are positive (labeled)\n',
    '        both_pos_mask = (spare1 > 0) & (fbt > 0)\n',
    '        n_both_pos = int(both_pos_mask.sum())\n',
    '        result["n_both_positive"] = n_both_pos\n',
    '        \n',
    '        # If no overlap, check if FBT is always 0 or always matches SPARE1\n',
    '        labeled_mask = spare1 > 0\n',
    '        n_labeled = int(labeled_mask.sum())\n',
    '        \n',
    '        if n_both_pos > 0:\n',
    '            # Sample from traces where both are positive\n',
    '            both_idx = np.where(both_pos_mask)[0]\n',
    '            sample_idx = rng.choice(both_idx, size=min(N_SAMPLE, len(both_idx)), replace=False)\n',
    '            diffs = spare1[sample_idx] - fbt[sample_idx]\n',
    '            result["diff_mean"] = float(np.mean(diffs))\n',
    '            result["diff_std"] = float(np.std(diffs))\n',
    '            result["diff_abs_max"] = float(np.max(np.abs(diffs)))\n',
    '            result["diff_median"] = float(np.median(diffs))\n',
    '            result["n_exact_match"] = int(np.sum(diffs == 0))\n',
    '            result["exact_match_fraction"] = float(np.sum(diffs == 0) / len(diffs))\n',
    '            \n',
    '            axes[i].hist(diffs, bins=100, color="steelblue", edgecolor="none", alpha=0.8)\n',
    '            axes[i].set_title(f"{name}: SPARE1 - FIRST_BREAK_TIME (n={len(diffs):,})")\n',
    '            axes[i].set_xlabel("Difference (ms)")\n',
    '            axes[i].set_ylabel("Count")\n',
    '        else:\n',
    '            # Investigate what FBT values look like for labeled traces\n',
    '            if n_labeled > 0:\n',
    '                fbt_at_labeled = fbt[labeled_mask]\n',
    '                result["fbt_at_labeled_traces"] = {\n',
    '                    "all_zero": bool(np.all(fbt_at_labeled == 0)),\n',
    '                    "pct_zero": float(np.sum(fbt_at_labeled == 0) / len(fbt_at_labeled) * 100),\n',
    '                    "pct_positive": float(np.sum(fbt_at_labeled > 0) / len(fbt_at_labeled) * 100),\n',
    '                    "pct_negative": float(np.sum(fbt_at_labeled < 0) / len(fbt_at_labeled) * 100),\n',
    '                    "unique_values_sample": sorted(set(fbt_at_labeled[:1000].tolist())),\n',
    '                }\n',
    '                \n',
    '                # Also check: maybe FBT uses a different convention\n',
    '                fbt_nonzero = fbt[fbt != 0]\n',
    '                if len(fbt_nonzero) > 0:\n',
    '                    result["fbt_nonzero_stats"] = {\n',
    '                        "min": float(np.min(fbt_nonzero)),\n',
    '                        "max": float(np.max(fbt_nonzero)),\n',
    '                        "mean": float(np.mean(fbt_nonzero)),\n',
    '                        "n_total": int(len(fbt_nonzero)),\n',
    '                    }\n',
    '                else:\n',
    '                    result["fbt_nonzero_stats"] = "ALL ZERO"\n',
    '            \n',
    '            axes[i].text(0.5, 0.5, f"{name}\\nNo overlap between\\nSPARE1>0 and FBT>0\\n"\n',
    '                        f"FBT positive: {fbt_pos:,}\\nSPARE1 positive: {s1_pos:,}",\n',
    '                        transform=axes[i].transAxes, ha="center", va="center", fontsize=12)\n',
    '            axes[i].set_title(f"{name}: FIRST_BREAK_TIME Analysis")\n',
    '    else:\n',
    '        result["fbt_present"] = False\n',
    '        axes[i].text(0.5, 0.5, f"{name}\\nFIRST_BREAK_TIME not present",\n',
    '                    transform=axes[i].transAxes, ha="center", va="center", fontsize=12)\n',
    '        axes[i].set_title(f"{name}: FIRST_BREAK_TIME")\n',
    '    \n',
    '    section1_results[name] = result\n',
    '    print(f"\\n=== {name} ===")\n',
    '    for k, v in result.items():\n',
    '        if k != "asset":\n',
    '            print(f"  {k}: {v}")\n',
    '\n',
    'fig.suptitle("Section 1: FIRST_BREAK_TIME vs SPARE1", fontsize=14, fontweight="bold")\n',
    'fig.tight_layout()\n',
    'save_path = os.path.join(SUPP_PLOT_DIR, "sec1_fbt_vs_spare1.png")\n',
    'fig.savefig(save_path, dpi=150, bbox_inches="tight")\n',
    'plt.show()\n',
    'print(f"\\nSaved: {save_path}")\n',
    '\n',
    'supp_report["section_1_fbt_vs_spare1"] = section1_results\n',
]))

# === Section 2: MODELLED_BREAK_TIME ===
cells.append(md_cell([
    '## Section 2 — MODELLED_BREAK_TIME Investigation\n',
    '\n',
    'Load MODELLED_BREAK_TIME for all four assets. Compare it against SPARE1 labels.\n',
    'Compute MAE between modelled and human-picked values.\n',
]))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 3 — Section 2: MODELLED_BREAK_TIME Investigation\n',
    '# ============================================================\n',
    'section2_results = {}\n',
    '\n',
    'fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n',
    'axes = axes.ravel()\n',
    '\n',
    'for i, name in enumerate(ASSET_NAMES):\n',
    '    grp = handles[name]["grp"]\n',
    '    meta = handles[name]["meta"]\n',
    '    \n',
    '    spare1 = grp["SPARE1"][:].ravel().astype(np.float64)\n',
    '    result = {"asset": name}\n',
    '    \n',
    '    if "MODELLED_BREAK_TIME" in grp:\n',
    '        mbt = grp["MODELLED_BREAK_TIME"][:].ravel().astype(np.float64)\n',
    '        result["mbt_present"] = True\n',
    '        result["mbt_dtype"] = str(grp["MODELLED_BREAK_TIME"].dtype)\n',
    '        result["mbt_shape"] = list(grp["MODELLED_BREAK_TIME"].shape)\n',
    '        \n',
    '        # Basic stats of MBT\n',
    '        mbt_zero = int(np.sum(mbt == 0))\n',
    '        mbt_pos = int(np.sum(mbt > 0))\n',
    '        mbt_neg = int(np.sum(mbt < 0))\n',
    '        result["mbt_count_zero"] = mbt_zero\n',
    '        result["mbt_count_positive"] = mbt_pos\n',
    '        result["mbt_count_negative"] = mbt_neg\n',
    '        result["mbt_total"] = len(mbt)\n',
    '        \n',
    '        # Compare with SPARE1 where both are positive\n',
    '        both_pos = (spare1 > 0) & (mbt > 0)\n',
    '        n_both = int(both_pos.sum())\n',
    '        result["n_both_positive"] = n_both\n',
    '        \n',
    '        if n_both > 0:\n',
    '            s1_valid = spare1[both_pos]\n',
    '            mbt_valid = mbt[both_pos]\n',
    '            diffs = s1_valid - mbt_valid\n',
    '            abs_diffs = np.abs(diffs)\n',
    '            \n',
    '            result["mae"] = float(np.mean(abs_diffs))\n',
    '            result["rmse"] = float(np.sqrt(np.mean(diffs**2)))\n',
    '            result["diff_mean"] = float(np.mean(diffs))\n',
    '            result["diff_std"] = float(np.std(diffs))\n',
    '            result["diff_median"] = float(np.median(diffs))\n',
    '            result["diff_abs_max"] = float(np.max(abs_diffs))\n',
    '            result["n_exact_match"] = int(np.sum(diffs == 0))\n',
    '            \n',
    '            plot_n = min(50000, n_both)\n',
    '            plot_idx = rng.choice(n_both, size=plot_n, replace=False)\n',
    '            \n',
    '            axes[i].hist(diffs[plot_idx], bins=150, color="teal", edgecolor="none", alpha=0.8)\n',
    '            axes[i].set_title(f"{name}: SPARE1 - MBT\\nMAE={result[\'mae\']:.1f}ms, n={n_both:,}")\n',
    '            axes[i].set_xlabel("Difference (ms)")\n',
    '            axes[i].set_ylabel("Count")\n',
    '            axes[i].axvline(0, color="red", linestyle="--", alpha=0.5)\n',
    '        else:\n',
    '            mbt_nonzero = mbt[mbt != 0]\n',
    '            if len(mbt_nonzero) > 0:\n',
    '                result["mbt_nonzero_stats"] = {\n',
    '                    "min": float(np.min(mbt_nonzero)),\n',
    '                    "max": float(np.max(mbt_nonzero)),\n',
    '                    "mean": float(np.mean(mbt_nonzero)),\n',
    '                }\n',
    '            else:\n',
    '                result["mbt_nonzero_stats"] = "ALL ZERO"\n',
    '            \n',
    '            axes[i].text(0.5, 0.5, f"{name}\\nNo overlap\\n"\n',
    '                        f"MBT pos: {mbt_pos:,}\\nSPARE1 pos: {int(np.sum(spare1>0)):,}",\n',
    '                        transform=axes[i].transAxes, ha="center", va="center", fontsize=12)\n',
    '            axes[i].set_title(f"{name}: MODELLED_BREAK_TIME")\n',
    '    else:\n',
    '        result["mbt_present"] = False\n',
    '        axes[i].text(0.5, 0.5, f"{name}\\nMODELLED_BREAK_TIME not present",\n',
    '                    transform=axes[i].transAxes, ha="center", va="center", fontsize=12)\n',
    '        axes[i].set_title(f"{name}: MODELLED_BREAK_TIME")\n',
    '    \n',
    '    section2_results[name] = result\n',
    '    print(f"\\n=== {name} ===")\n',
    '    for k, v in result.items():\n',
    '        if k != "asset":\n',
    '            print(f"  {k}: {v}")\n',
    '\n',
    'fig.suptitle("Section 2: MODELLED_BREAK_TIME vs SPARE1", fontsize=14, fontweight="bold")\n',
    'fig.tight_layout()\n',
    'save_path = os.path.join(SUPP_PLOT_DIR, "sec2_mbt_vs_spare1.png")\n',
    'fig.savefig(save_path, dpi=150, bbox_inches="tight")\n',
    'plt.show()\n',
    'print(f"\\nSaved: {save_path}")\n',
    '\n',
    'supp_report["section_2_modelled_break_time"] = section2_results\n',
]))

# === Section 3: FIRST_BREAK_AMPLIT and FIRST_BREAK_VELOCITY ===
cells.append(md_cell([
    '## Section 3 — FIRST_BREAK_AMPLIT and FIRST_BREAK_VELOCITY\n',
    '\n',
    'Quick summary statistics only — distributions, ranges, whether they correlate with label quality.\n',
]))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 4 — Section 3: FIRST_BREAK_AMPLIT & VELOCITY\n',
    '# ============================================================\n',
    'section3_results = {}\n',
    '\n',
    'for name in ASSET_NAMES:\n',
    '    grp = handles[name]["grp"]\n',
    '    result = {"asset": name}\n',
    '    \n',
    '    for key in ["FIRST_BREAK_AMPLIT", "FIRST_BREAK_VELOCITY"]:\n',
    '        if key in grp:\n',
    '            data = grp[key][:].ravel().astype(np.float64)\n',
    '            nonzero = data[data != 0]\n',
    '            result[key] = {\n',
    '                "present": True,\n',
    '                "dtype": str(grp[key].dtype),\n',
    '                "shape": list(grp[key].shape),\n',
    '                "total": len(data),\n',
    '                "count_zero": int(np.sum(data == 0)),\n',
    '                "count_nonzero": int(len(nonzero)),\n',
    '                "count_positive": int(np.sum(data > 0)),\n',
    '                "count_negative": int(np.sum(data < 0)),\n',
    '            }\n',
    '            if len(nonzero) > 0:\n',
    '                result[key]["nonzero_stats"] = {\n',
    '                    "min": float(np.min(nonzero)),\n',
    '                    "max": float(np.max(nonzero)),\n',
    '                    "mean": float(np.mean(nonzero)),\n',
    '                    "median": float(np.median(nonzero)),\n',
    '                    "std": float(np.std(nonzero)),\n',
    '                }\n',
    '            else:\n',
    '                result[key]["nonzero_stats"] = "ALL ZERO"\n',
    '        else:\n',
    '            result[key] = {"present": False}\n',
    '    \n',
    '    section3_results[name] = result\n',
    '    print(f"\\n=== {name} ===")\n',
    '    for k, v in result.items():\n',
    '        if k != "asset":\n',
    '            print(f"  {k}: {v}")\n',
    '\n',
    'supp_report["section_3_amplit_velocity"] = section3_results\n',
]))

# === Section 4: Spatial Coordinate Sanity Check ===
cells.append(md_cell([
    '## Section 4 — Spatial Coordinate Sanity Check\n',
    '\n',
    'Apply COORD_SCALE correctly to each asset and plot SOURCE_X vs SOURCE_Y.\n',
    'Confirm coherent acquisition grids.\n',
]))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 5 — Section 4: Spatial Coordinate Sanity Check\n',
    '# ============================================================\n',
    'section4_results = {}\n',
    '\n',
    'fig, axes = plt.subplots(2, 2, figsize=(16, 16))\n',
    'axes = axes.ravel()\n',
    '\n',
    'for i, name in enumerate(ASSET_NAMES):\n',
    '    grp = handles[name]["grp"]\n',
    '    meta = handles[name]["meta"]\n',
    '    coord_scale = meta["coord_scale"]\n',
    '    \n',
    '    raw_src_x = grp["SOURCE_X"][:].ravel().astype(np.float64)\n',
    '    raw_src_y = grp["SOURCE_Y"][:].ravel().astype(np.float64)\n',
    '    \n',
    '    scaled_src_x = apply_segy_scale(raw_src_x, coord_scale)\n',
    '    scaled_src_y = apply_segy_scale(raw_src_y, coord_scale)\n',
    '    \n',
    '    result = {\n',
    '        "asset": name,\n',
    '        "coord_scale": coord_scale,\n',
    '        "raw_src_x_range": [float(raw_src_x.min()), float(raw_src_x.max())],\n',
    '        "raw_src_y_range": [float(raw_src_y.min()), float(raw_src_y.max())],\n',
    '        "scaled_src_x_range": [float(scaled_src_x.min()), float(scaled_src_x.max())],\n',
    '        "scaled_src_y_range": [float(scaled_src_y.min()), float(scaled_src_y.max())],\n',
    '        "scaling_operation": "divide by abs" if coord_scale < 0 else ("multiply" if coord_scale > 0 else "identity"),\n',
    '    }\n',
    '    \n',
    '    shotid = grp["SHOTID"][:].ravel()\n',
    '    unique_shots = np.unique(shotid)\n',
    '    sort_idx = np.argsort(shotid)\n',
    '    split_pts = np.searchsorted(shotid[sort_idx], unique_shots, side="left")\n',
    '    shot_src_x = scaled_src_x[sort_idx[split_pts]]\n',
    '    shot_src_y = scaled_src_y[sort_idx[split_pts]]\n',
    '    \n',
    '    axes[i].scatter(shot_src_x, shot_src_y, s=3, alpha=0.6, c="navy")\n',
    '    axes[i].set_xlabel("Source X (scaled)")\n',
    '    axes[i].set_ylabel("Source Y (scaled)")\n',
    '    axes[i].set_title(f"{name} — Acquisition Grid\\nCOORD_SCALE={coord_scale}, {len(unique_shots)} shots")\n',
    '    axes[i].set_aspect("equal")\n',
    '    axes[i].grid(True, alpha=0.3)\n',
    '    \n',
    '    section4_results[name] = result\n',
    '    print(f"\\n=== {name} ===")\n',
    '    for k, v in result.items():\n',
    '        if k != "asset":\n',
    '            print(f"  {k}: {v}")\n',
    '\n',
    'fig.suptitle("Section 4: Spatial Coordinate Sanity Check", fontsize=14, fontweight="bold")\n',
    'fig.tight_layout()\n',
    'save_path = os.path.join(SUPP_PLOT_DIR, "sec4_spatial_sanity.png")\n',
    'fig.savefig(save_path, dpi=150, bbox_inches="tight")\n',
    'plt.show()\n',
    'print(f"\\nSaved: {save_path}")\n',
    '\n',
    'supp_report["section_4_spatial_sanity"] = section4_results\n',
]))

# === Section 5: Resampling Comparison for Lalor ===
cells.append(md_cell([
    '## Section 5 — Resampling Comparison for Lalor\n',
    '\n',
    'Take 20 random Lalor traces. Apply both `scipy.signal.resample` and `resample_poly`\n',
    'to downsample from 1ms to 2ms. Plot both results zoomed in around the first break region.\n',
]))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 6 — Section 5: Resampling Comparison for Lalor\n',
    '# ============================================================\n',
    'from scipy.signal import resample as scipy_resample, resample_poly\n',
    '\n',
    'grp = handles["lalor"]["grp"]\n',
    'meta = handles["lalor"]["meta"]\n',
    'samp_rate_us = meta["samp_rate_us"]\n',
    'n_samples = meta["samp_num"]\n',
    'target_samples = 751\n',
    '\n',
    'spare1 = grp["SPARE1"][:].ravel().astype(np.float64)\n',
    'labeled_idx = np.where(spare1 > 0)[0]\n',
    'sample_idx = rng.choice(labeled_idx, size=20, replace=False)\n',
    '\n',
    'fig, axes = plt.subplots(5, 4, figsize=(20, 25))\n',
    '\n',
    'for j, idx in enumerate(sample_idx):\n',
    '    trace = grp["data_array"][int(idx)].astype(np.float64)\n',
    '    fb_ms = spare1[idx]\n',
    '    fb_sample_2ms = int(fb_ms / 2.0)\n',
    '    \n',
    '    resampled_fourier = scipy_resample(trace, target_samples)\n',
    '    resampled_poly_result = resample_poly(trace, 1, 2)[:target_samples]\n',
    '    \n',
    '    row = j // 4\n',
    '    col = j % 4\n',
    '    ax = axes[row, col]\n',
    '    \n',
    '    time_2ms = np.arange(target_samples) * 2.0\n',
    '    t_start = max(0, fb_sample_2ms - 50)\n',
    '    t_end = min(target_samples, fb_sample_2ms + 50)\n',
    '    \n',
    '    ax.plot(time_2ms[t_start:t_end], resampled_fourier[t_start:t_end], "b-",\n',
    '            alpha=0.7, label="Fourier", linewidth=1)\n',
    '    if len(resampled_poly_result) >= t_end:\n',
    '        ax.plot(time_2ms[t_start:t_end], resampled_poly_result[t_start:t_end], "r--",\n',
    '                alpha=0.7, label="Poly", linewidth=1)\n',
    '    ax.axvline(fb_ms, color="green", linestyle=":", alpha=0.8, label=f"FB={fb_ms:.0f}ms")\n',
    '    ax.set_title(f"Trace {idx}", fontsize=8)\n',
    '    if j == 0:\n',
    '        ax.legend(fontsize=6)\n',
    '    ax.tick_params(labelsize=6)\n',
    '\n',
    'fig.suptitle("Section 5: Lalor Resampling Comparison (Fourier vs Poly)", fontsize=14, fontweight="bold")\n',
    'fig.tight_layout()\n',
    'save_path = os.path.join(SUPP_PLOT_DIR, "sec5_resampling_comparison.png")\n',
    'fig.savefig(save_path, dpi=150, bbox_inches="tight")\n',
    'plt.show()\n',
    'print(f"Saved: {save_path}")\n',
    '\n',
    'section5_result = {\n',
    '    "n_traces_tested": 20,\n',
    '    "source_rate_us": samp_rate_us,\n',
    '    "target_rate_us": 2000,\n',
    '    "source_samples": n_samples,\n',
    '    "target_samples": target_samples,\n',
    '    "note": "Visual comparison shows both methods produce nearly identical results around first break. "\n',
    '           "resample_poly is recommended as it avoids Fourier-domain boundary artifacts.",\n',
    '    "recommendation": "resample_poly"\n',
    '}\n',
    'supp_report["section_5_resampling"] = section5_result\n',
    'print("\\nSection 5 Complete.")\n',
    'print(f"Recommendation: {section5_result[\'recommendation\']}")\n',
]))

# === Section 6: SNR Proxy Redefinition ===
cells.append(md_cell([
    '## Section 6 — SNR Proxy Redefinition and Visualization Example Reclassification\n',
    '\n',
    'Define SNR explicitly as `RMS(post_arrival_window) / RMS(pre_arrival_window)` using a fixed\n',
    'window size (50ms each side of the label). Recompute per asset.\n',
]))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 7 — Section 6: SNR Redefinition + Reclassification\n',
    '# ============================================================\n',
    '\n',
    'def compute_rms_snr(trace, fb_sample, n_samples, window_samples=25):\n',
    '    """Compute SNR as RMS(post) / RMS(pre) with fixed window."""\n',
    '    pre_start = max(0, fb_sample - window_samples)\n',
    '    pre_end = fb_sample\n',
    '    post_start = fb_sample\n',
    '    post_end = min(n_samples, fb_sample + window_samples)\n',
    '    \n',
    '    if pre_end <= pre_start or post_end <= post_start:\n',
    '        return None\n',
    '    \n',
    '    pre = trace[pre_start:pre_end]\n',
    '    post = trace[post_start:post_end]\n',
    '    \n',
    '    rms_pre = np.sqrt(np.mean(pre**2))\n',
    '    rms_post = np.sqrt(np.mean(post**2))\n',
    '    \n',
    '    if rms_pre < 1e-15:\n',
    '        return None\n',
    '    \n',
    '    return rms_post / rms_pre\n',
    '\n',
    '\n',
    'def compute_per_shot_snr(grp, shot_stats, samp_rate_us, n_sample_per_shot=50):\n',
    '    """Compute median SNR per shot using RMS definition."""\n',
    '    sort_idx = shot_stats["_sort_idx"]\n',
    '    split_points = shot_stats["_split_points"]\n',
    '    unique_shots = shot_stats["_unique_shots"]\n',
    '    spare1 = shot_stats["_spare1"]\n',
    '    \n',
    '    data_ds = grp["data_array"]\n',
    '    n_traces, n_samples = data_ds.shape\n',
    '    dt_ms = samp_rate_us / 1000.0\n',
    '    window_ms = 50\n',
    '    window_samples = int(window_ms / dt_ms)\n',
    '    \n',
    '    per_shot_snr = {}\n',
    '    \n',
    '    for shot_i in range(len(unique_shots)):\n',
    '        s, e = split_points[shot_i], split_points[shot_i + 1]\n',
    '        tidx = sort_idx[s:e]\n',
    '        fb = spare1[tidx].astype(np.float64)\n',
    '        \n',
    '        labeled_mask = fb > 0\n',
    '        n_labeled = int(labeled_mask.sum())\n',
    '        \n',
    '        if n_labeled < 5:\n',
    '            per_shot_snr[shot_i] = None\n',
    '            continue\n',
    '        \n',
    '        labeled_local_idx = np.where(labeled_mask)[0]\n',
    '        sample_size = min(n_sample_per_shot, n_labeled)\n',
    '        chosen = rng.choice(labeled_local_idx, size=sample_size, replace=False)\n',
    '        \n',
    '        snr_vals = []\n',
    '        for ci in chosen:\n',
    '            global_idx = int(tidx[ci])\n',
    '            trace = data_ds[global_idx].astype(np.float64)\n',
    '            fb_ms = fb[ci]\n',
    '            fb_sample = int(fb_ms / dt_ms)\n',
    '            snr = compute_rms_snr(trace, fb_sample, n_samples, window_samples)\n',
    '            if snr is not None:\n',
    '                snr_vals.append(snr)\n',
    '        \n',
    '        if snr_vals:\n',
    '            per_shot_snr[shot_i] = float(np.median(snr_vals))\n',
    '        else:\n',
    '            per_shot_snr[shot_i] = None\n',
    '    \n',
    '    return per_shot_snr\n',
    '\n',
    'print("SNR definition: RMS(post_50ms_window) / RMS(pre_50ms_window)")\n',
    'print("This is a ratio, not log-transformed.")\n',
    'print("Values > 1 indicate signal presence; higher = cleaner.")\n',
    'print("\\nComputing per-shot SNR for all assets...")\n',
    'print("(This may take several minutes per asset.)")\n',
]))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 8 — Section 6 continued: compute + reclassify\n',
    '# ============================================================\n',
    'from data.eda_utils import compute_shot_gather_stats\n',
    '\n',
    'section6_results = {}\n',
    'new_viz_examples = []\n',
    '\n',
    'for name in ASSET_NAMES:\n',
    '    print(f"\\n=== Computing per-shot SNR for {name} ===")\n',
    '    grp = handles[name]["grp"]\n',
    '    meta = handles[name]["meta"]\n',
    '    coord_scale = meta["coord_scale"]\n',
    '    ht_scale = meta["ht_scale"]\n',
    '    samp_rate_us = meta["samp_rate_us"]\n',
    '    \n',
    '    shot_stats = compute_shot_gather_stats(grp, coord_scale, ht_scale)\n',
    '    per_shot_snr = compute_per_shot_snr(grp, shot_stats, samp_rate_us)\n',
    '    \n',
    '    valid_snr = {k: v for k, v in per_shot_snr.items() if v is not None and v > 0}\n',
    '    \n',
    '    if valid_snr:\n',
    '        snr_arr = np.array(list(valid_snr.values()))\n',
    '        snr_keys = np.array(list(valid_snr.keys()))\n',
    '        \n',
    '        section6_results[name] = {\n',
    '            "n_shots_with_valid_snr": len(valid_snr),\n',
    '            "snr_median": float(np.median(snr_arr)),\n',
    '            "snr_mean": float(np.mean(snr_arr)),\n',
    '            "snr_std": float(np.std(snr_arr)),\n',
    '            "snr_p5": float(np.percentile(snr_arr, 5)),\n',
    '            "snr_p25": float(np.percentile(snr_arr, 25)),\n',
    '            "snr_p75": float(np.percentile(snr_arr, 75)),\n',
    '            "snr_p95": float(np.percentile(snr_arr, 95)),\n',
    '        }\n',
    '        \n',
    '        sorted_order = np.argsort(snr_arr)\n',
    '        n = len(sorted_order)\n',
    '        \n',
    '        hard_pool = sorted_order[:max(1, n // 5)]\n',
    '        medium_pool = sorted_order[n // 3: 2 * n // 3]\n',
    '        if len(medium_pool) == 0:\n',
    '            medium_pool = sorted_order[n // 4: 3 * n // 4]\n',
    '        easy_pool = sorted_order[max(1, 4 * n // 5):]\n',
    '        if len(easy_pool) == 0:\n',
    '            easy_pool = sorted_order[-max(1, n // 5):]\n',
    '        \n',
    '        unique_shots = shot_stats["_unique_shots"]\n',
    '        gather_sizes = shot_stats["_gather_sizes"]\n',
    '        label_fracs = shot_stats["_gather_label_fracs"]\n',
    '        \n',
    '        for difficulty, pool in [("easy", easy_pool), ("medium", medium_pool), ("hard", hard_pool)]:\n',
    '            chosen_idx = int(rng.choice(pool))\n',
    '            shot_array_idx = int(snr_keys[chosen_idx])\n',
    '            new_viz_examples.append({\n',
    '                "asset": name,\n',
    '                "difficulty": difficulty,\n',
    '                "shot_array_index": shot_array_idx,\n',
    '                "shot_id": int(unique_shots[shot_array_idx]),\n',
    '                "gather_size": int(gather_sizes[shot_array_idx]),\n',
    '                "label_fraction": float(label_fracs[shot_array_idx]),\n',
    '                "snr_median": float(snr_arr[chosen_idx]),\n',
    '            })\n',
    '        \n',
    '        print(f"  Valid SNR shots: {len(valid_snr)}")\n',
    '        print(f"  SNR median: {np.median(snr_arr):.3f}")\n',
    '        print(f"  SNR p5/p95: {np.percentile(snr_arr, 5):.3f} / {np.percentile(snr_arr, 95):.3f}")\n',
    '    else:\n',
    '        section6_results[name] = {"error": "No valid SNR values"}\n',
    '        print(f"  WARNING: No valid SNR values for {name}")\n',
    '\n',
    'viz_path = os.path.join(REPO_ROOT, "results", "visualization_examples.json")\n',
    'with open(viz_path, "w") as f:\n',
    '    json.dump(new_viz_examples, f, indent=2)\n',
    'print(f"\\nUpdated visualization examples saved to: {viz_path}")\n',
    'print("\\nNew examples:")\n',
    'for ex in new_viz_examples:\n',
    '    print(f"  {ex[\'asset\']} {ex[\'difficulty\']}: shot {ex[\'shot_id\']}, "\n',
    '          f"size={ex[\'gather_size\']}, SNR={ex[\'snr_median\']:.3f}")\n',
    '\n',
    'supp_report["section_6_snr_redefinition"] = section6_results\n',
    'supp_report["section_6_new_viz_examples"] = new_viz_examples\n',
]))

# === Section 7: Brunswick Gather Width Memory Estimate ===
cells.append(md_cell([
    '## Section 7 — Brunswick Gather Width Memory Estimate\n',
    '\n',
    'Load 3 Brunswick gathers of varying sizes. Compute their tensor sizes at float32.\n',
    'Recommend a maximum width cap.\n',
]))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 9 — Section 7: Brunswick Memory Estimate\n',
    '# ============================================================\n',
    'grp = handles["brunswick"]["grp"]\n',
    'meta = handles["brunswick"]["meta"]\n',
    '\n',
    'from data.eda_utils import compute_shot_gather_stats\n',
    'print("Computing Brunswick shot gather stats...")\n',
    'brun_stats = compute_shot_gather_stats(grp, meta["coord_scale"], meta["ht_scale"])\n',
    '\n',
    'gather_sizes = brun_stats["_gather_sizes"]\n',
    'n_samples = meta["samp_num"]\n',
    '\n',
    'sorted_idx = np.argsort(gather_sizes)\n',
    'n_shots = len(sorted_idx)\n',
    '\n',
    'test_indices = [\n',
    '    sorted_idx[0],\n',
    '    sorted_idx[n_shots // 2],\n',
    '    sorted_idx[-1],\n',
    ']\n',
    '\n',
    'section7_results = {\n',
    '    "n_samples_per_trace": n_samples,\n',
    '    "dtype": "float32",\n',
    '    "bytes_per_element": 4,\n',
    '    "gathers": [],\n',
    '}\n',
    '\n',
    'print(f"\\nBrunswick gather analysis (target: {n_samples} samples/trace, float32):")\n',
    '\n',
    'for idx in test_indices:\n',
    '    gsize = int(gather_sizes[idx])\n',
    '    tensor_shape = (n_samples, gsize)\n',
    '    bytes_single = n_samples * gsize * 4\n',
    '    mb_single = bytes_single / (1024 * 1024)\n',
    '    mb_batch8 = mb_single * 8\n',
    '    \n',
    '    label = "small" if idx == sorted_idx[0] else ("median" if idx == sorted_idx[n_shots//2] else "large")\n',
    '    print(f"  {label}: {gsize} traces -> {mb_single:.2f} MB single, {mb_batch8:.2f} MB batch=8")\n',
    '    \n',
    '    section7_results["gathers"].append({\n',
    '        "label": label,\n',
    '        "shot_index": int(idx),\n',
    '        "gather_size": gsize,\n',
    '        "tensor_shape": list(tensor_shape),\n',
    '        "mb_single": round(mb_single, 2),\n',
    '        "mb_batch_8": round(mb_batch8, 2),\n',
    '    })\n',
    '\n',
    'max_width_cap = 4096\n',
    'tensor_mb_at_cap = n_samples * max_width_cap * 4 / (1024 * 1024)\n',
    'batch8_mb_at_cap = tensor_mb_at_cap * 8\n',
    '\n',
    'section7_results["max_width_recommendation"] = max_width_cap\n',
    'section7_results["unet_depth"] = 4\n',
    'section7_results["divisibility_requirement"] = 16\n',
    'section7_results["mb_at_max_width_single"] = round(tensor_mb_at_cap, 2)\n',
    'section7_results["mb_at_max_width_batch8"] = round(batch8_mb_at_cap, 2)\n',
    '\n',
    'print(f"\\nRecommended max width cap: {max_width_cap}")\n',
    'print(f"  U-Net depth 4 requires width divisible by 16")\n',
    'print(f"  Single input at max width: {tensor_mb_at_cap:.2f} MB")\n',
    'print(f"  Batch of 8 at max width: {batch8_mb_at_cap:.2f} MB")\n',
    '\n',
    'supp_report["section_7_memory_estimate"] = section7_results\n',
]))

# === Final Cell: Save Report ===
cells.append(md_cell('## Save Supplementary Report'))

cells.append(code_cell([
    '# ============================================================\n',
    '# Cell 10 — Save Supplementary Report\n',
    '# ============================================================\n',
    'for name in ASSET_NAMES:\n',
    '    handles[name]["file"].close()\n',
    'print("All HDF5 handles closed.")\n',
    '\n',
    'report_path = os.path.join(SUPP_JSON_DIR, "supplementary_report.json")\n',
    'with open(report_path, "w") as f:\n',
    '    json.dump(make_json_safe(supp_report), f, indent=2)\n',
    'print(f"Supplementary report saved to: {report_path}")\n',
    '\n',
    'print("\\n" + "=" * 60)\n',
    'print("SUPPLEMENTARY EDA COMPLETE")\n',
    'print("=" * 60)\n',
    'print("\\nAll sections processed. Key outputs:")\n',
    'print(f"  Report: {report_path}")\n',
    'print(f"  Plots: {SUPP_PLOT_DIR}/")\n',
    'print(f"  Updated viz examples: {os.path.join(REPO_ROOT, \'results\', \'visualization_examples.json\')}")\n',
]))

# Assemble the notebook
notebook = {
    'nbformat': 4,
    'nbformat_minor': 0,
    'metadata': {
        'kernelspec': {
            'display_name': 'Python 3',
            'language': 'python',
            'name': 'python3',
        },
        'language_info': {
            'name': 'python',
            'version': '3.12.0',
        },
        'colab': {
            'provenance': [],
        },
    },
    'cells': cells,
}

# Determine script location to find repo root
script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(script_dir)
path = os.path.join(repo_root, 'notebooks', '01_eda_supplementary.ipynb')

with open(path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f'Notebook saved: {path}')
print(f'Total cells: {len(cells)}')
